
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class CommandLineJobRunnerDialog
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textviewOutput;
		
		private global::Gtk.Button cancelButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.CommandLineJobRunnerDialog
			this.Name = "PhoneGapProjectAssistant.CommandLineJobRunnerDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Command Line Job Runner");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Internal child PhoneGapProjectAssistant.CommandLineJobRunnerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewOutput = new global::Gtk.TextView ();
			global::Gtk.Tooltips w2 = new Gtk.Tooltips ();
			w2.SetTip (this.textviewOutput, "Terminal output", "Terminal output");
			this.textviewOutput.CanFocus = true;
			this.textviewOutput.Name = "textviewOutput";
			this.textviewOutput.Editable = false;
			this.textviewOutput.CursorVisible = false;
			this.GtkScrolledWindow.Add (this.textviewOutput);
			w1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.GtkScrolledWindow]));
			w4.Position = 0;
			// Internal child PhoneGapProjectAssistant.CommandLineJobRunnerDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanDefault = true;
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.cancelButton.Image = w6;
			this.AddActionWidget (this.cancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.cancelButton]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 534;
			this.DefaultHeight = 339;
			this.Show ();
			this.cancelButton.Clicked += new global::System.EventHandler (this.cancelClick);
		}
	}
}
