
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class PlatformWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox PreferencesTitleBox;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow PreferencesScrolledBox;
		
		private global::Gtk.VBox preferenceContentVbox;
		
		private global::Gtk.Button addPreferenceButton;
		
		private global::Gtk.HBox IconsTitleBox;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ScrolledWindow IconsScrolledBox;
		
		private global::Gtk.VBox iconsVbox;
		
		private global::Gtk.Button addIconButton;
		
		private global::Gtk.HBox SplashTitleBox;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ScrolledWindow SplashScrolledBox;
		
		private global::Gtk.VBox splashesVbox;
		
		private global::Gtk.Button addSplashButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.PlatformWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PhoneGapProjectAssistant.PlatformWidget";
			// Container child PhoneGapProjectAssistant.PlatformWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.PreferencesTitleBox = new global::Gtk.HBox ();
			this.PreferencesTitleBox.Name = "PreferencesTitleBox";
			this.PreferencesTitleBox.Spacing = 6;
			// Container child PreferencesTitleBox.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Global Prefrences :</span>");
			this.label2.UseMarkup = true;
			this.label2.UseUnderline = true;
			this.PreferencesTitleBox.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.PreferencesTitleBox [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add (this.PreferencesTitleBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.PreferencesTitleBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.PreferencesScrolledBox = new global::Gtk.ScrolledWindow ();
			this.PreferencesScrolledBox.Name = "PreferencesScrolledBox";
			this.PreferencesScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.PreferencesScrolledBox.BorderWidth = ((uint)(3));
			// Container child PreferencesScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.preferenceContentVbox = new global::Gtk.VBox ();
			this.preferenceContentVbox.Name = "preferenceContentVbox";
			this.preferenceContentVbox.Spacing = 6;
			// Container child preferenceContentVbox.Gtk.Box+BoxChild
			this.addPreferenceButton = new global::Gtk.Button ();
			this.addPreferenceButton.CanFocus = true;
			this.addPreferenceButton.Name = "addPreferenceButton";
			this.addPreferenceButton.UseUnderline = true;
			this.addPreferenceButton.BorderWidth = ((uint)(3));
			this.addPreferenceButton.Label = global::Mono.Unix.Catalog.GetString ("Add Preference");
			this.preferenceContentVbox.Add (this.addPreferenceButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.preferenceContentVbox [this.addPreferenceButton]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w3.Add (this.preferenceContentVbox);
			this.PreferencesScrolledBox.Add (w3);
			this.vbox1.Add (this.PreferencesScrolledBox);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.PreferencesScrolledBox]));
			w7.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.IconsTitleBox = new global::Gtk.HBox ();
			this.IconsTitleBox.Name = "IconsTitleBox";
			this.IconsTitleBox.Spacing = 6;
			// Container child IconsTitleBox.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Icons :</span>");
			this.label3.UseMarkup = true;
			this.IconsTitleBox.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.IconsTitleBox [this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.IconsTitleBox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.IconsTitleBox]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.IconsScrolledBox = new global::Gtk.ScrolledWindow ();
			this.IconsScrolledBox.CanFocus = true;
			this.IconsScrolledBox.Name = "IconsScrolledBox";
			this.IconsScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.IconsScrolledBox.BorderWidth = ((uint)(3));
			// Container child IconsScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.iconsVbox = new global::Gtk.VBox ();
			this.iconsVbox.Name = "iconsVbox";
			this.iconsVbox.Spacing = 6;
			// Container child iconsVbox.Gtk.Box+BoxChild
			this.addIconButton = new global::Gtk.Button ();
			this.addIconButton.CanFocus = true;
			this.addIconButton.Name = "addIconButton";
			this.addIconButton.UseUnderline = true;
			this.addIconButton.BorderWidth = ((uint)(3));
			this.addIconButton.Label = global::Mono.Unix.Catalog.GetString ("Add Icon");
			this.iconsVbox.Add (this.addIconButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.iconsVbox [this.addIconButton]));
			w11.PackType = ((global::Gtk.PackType)(1));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w10.Add (this.iconsVbox);
			this.IconsScrolledBox.Add (w10);
			this.vbox1.Add (this.IconsScrolledBox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.IconsScrolledBox]));
			w14.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SplashTitleBox = new global::Gtk.HBox ();
			this.SplashTitleBox.Name = "SplashTitleBox";
			this.SplashTitleBox.Spacing = 6;
			// Container child SplashTitleBox.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Splash Screens :</span>");
			this.label4.UseMarkup = true;
			this.SplashTitleBox.Add (this.label4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.SplashTitleBox [this.label4]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.SplashTitleBox);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SplashTitleBox]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SplashScrolledBox = new global::Gtk.ScrolledWindow ();
			this.SplashScrolledBox.CanFocus = true;
			this.SplashScrolledBox.Name = "SplashScrolledBox";
			this.SplashScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.SplashScrolledBox.BorderWidth = ((uint)(3));
			// Container child SplashScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w17 = new global::Gtk.Viewport ();
			w17.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.splashesVbox = new global::Gtk.VBox ();
			this.splashesVbox.WidthRequest = 0;
			this.splashesVbox.Name = "splashesVbox";
			this.splashesVbox.Spacing = 6;
			// Container child splashesVbox.Gtk.Box+BoxChild
			this.addSplashButton = new global::Gtk.Button ();
			this.addSplashButton.CanFocus = true;
			this.addSplashButton.Name = "addSplashButton";
			this.addSplashButton.UseUnderline = true;
			this.addSplashButton.BorderWidth = ((uint)(3));
			this.addSplashButton.Label = global::Mono.Unix.Catalog.GetString ("Add Splash Screen");
			this.splashesVbox.Add (this.addSplashButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.splashesVbox [this.addSplashButton]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w17.Add (this.splashesVbox);
			this.SplashScrolledBox.Add (w17);
			this.vbox1.Add (this.SplashScrolledBox);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SplashScrolledBox]));
			w21.Position = 5;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
