
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class PlatformWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.VBox preferenceContentVbox;
		
		private global::Gtk.Button addPreferenceButton;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Button addIconButton;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Button addSplashButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.PlatformWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PhoneGapProjectAssistant.PlatformWidget";
			// Container child PhoneGapProjectAssistant.PlatformWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Global Prefrences :</span>");
			this.label2.UseMarkup = true;
			this.label2.UseUnderline = true;
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.preferenceContentVbox = new global::Gtk.VBox ();
			this.preferenceContentVbox.Name = "preferenceContentVbox";
			this.preferenceContentVbox.Spacing = 6;
			// Container child preferenceContentVbox.Gtk.Box+BoxChild
			this.addPreferenceButton = new global::Gtk.Button ();
			this.addPreferenceButton.CanFocus = true;
			this.addPreferenceButton.Name = "addPreferenceButton";
			this.addPreferenceButton.UseUnderline = true;
			this.addPreferenceButton.BorderWidth = ((uint)(3));
			this.addPreferenceButton.Label = global::Mono.Unix.Catalog.GetString ("Add Preference");
			this.preferenceContentVbox.Add (this.addPreferenceButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.preferenceContentVbox [this.addPreferenceButton]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w3.Add (this.preferenceContentVbox);
			this.GtkScrolledWindow.Add (w3);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w7.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Icons :</span>");
			this.label3.UseMarkup = true;
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.scrolledwindow1.BorderWidth = ((uint)(3));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.addIconButton = new global::Gtk.Button ();
			this.addIconButton.CanFocus = true;
			this.addIconButton.Name = "addIconButton";
			this.addIconButton.UseUnderline = true;
			this.addIconButton.BorderWidth = ((uint)(3));
			this.addIconButton.Label = global::Mono.Unix.Catalog.GetString ("Add Icon");
			this.vbox3.Add (this.addIconButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.addIconButton]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			w10.Add (this.vbox3);
			this.scrolledwindow1.Add (w10);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w14.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Splash Screens :</span>");
			this.label4.UseMarkup = true;
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.scrolledwindow2.BorderWidth = ((uint)(3));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w17 = new global::Gtk.Viewport ();
			w17.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 0;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.addSplashButton = new global::Gtk.Button ();
			this.addSplashButton.CanFocus = true;
			this.addSplashButton.Name = "addSplashButton";
			this.addSplashButton.UseUnderline = true;
			this.addSplashButton.BorderWidth = ((uint)(3));
			this.addSplashButton.Label = global::Mono.Unix.Catalog.GetString ("Add Splash Screen");
			this.vbox2.Add (this.addSplashButton);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.addSplashButton]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w17.Add (this.vbox2);
			this.scrolledwindow2.Add (w17);
			this.vbox1.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow2]));
			w21.Position = 5;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
