
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class ProjectAssistantWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.ColorSelection colorselection1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.ProjectAssistantWindow
			this.Name = "PhoneGapProjectAssistant.ProjectAssistantWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("OpenNewWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child PhoneGapProjectAssistant.ProjectAssistantWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.colorselection1 = new global::Gtk.ColorSelection ();
			this.colorselection1.Name = "colorselection1";
			this.colorselection1.HasOpacityControl = true;
			this.fixed1.Add (this.colorselection1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.colorselection1]));
			w1.X = 276;
			w1.Y = 137;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 831;
			this.DefaultHeight = 451;
			this.Show ();
		}
	}
}
