
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class PlatformWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox PreferencesTitleBox;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow PreferencesScrolledBox;
		
		private global::Gtk.VBox preferenceContentVboxTop;
		
		private global::Gtk.VBox preferenceContentVbox;
		
		private global::Gtk.Button addPreferenceButton;
		
		private global::Gtk.HBox IconsTitleBox;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ScrolledWindow IconsScrolledBox;
		
		private global::Gtk.VBox iconsVbox;
		
		private global::Gtk.HBox SplashTitleBox;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ScrolledWindow SplashScrolledBox;
		
		private global::Gtk.VBox splashesVbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.PlatformWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PhoneGapProjectAssistant.PlatformWidget";
			// Container child PhoneGapProjectAssistant.PlatformWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.PreferencesTitleBox = new global::Gtk.HBox ();
			this.PreferencesTitleBox.Name = "PreferencesTitleBox";
			this.PreferencesTitleBox.Spacing = 6;
			this.PreferencesTitleBox.BorderWidth = ((uint)(3));
			// Container child PreferencesTitleBox.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Global Prefrences :</span>");
			this.label2.UseMarkup = true;
			this.label2.UseUnderline = true;
			this.PreferencesTitleBox.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.PreferencesTitleBox [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add (this.PreferencesTitleBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.PreferencesTitleBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.PreferencesScrolledBox = new global::Gtk.ScrolledWindow ();
			this.PreferencesScrolledBox.Name = "PreferencesScrolledBox";
			this.PreferencesScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.PreferencesScrolledBox.BorderWidth = ((uint)(3));
			// Container child PreferencesScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.preferenceContentVboxTop = new global::Gtk.VBox ();
			this.preferenceContentVboxTop.Name = "preferenceContentVboxTop";
			this.preferenceContentVboxTop.Spacing = 6;
			// Container child preferenceContentVboxTop.Gtk.Box+BoxChild
			this.preferenceContentVbox = new global::Gtk.VBox ();
			this.preferenceContentVbox.Name = "preferenceContentVbox";
			this.preferenceContentVbox.Spacing = 6;
			this.preferenceContentVboxTop.Add (this.preferenceContentVbox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.preferenceContentVboxTop [this.preferenceContentVbox]));
			w4.Position = 0;
			// Container child preferenceContentVboxTop.Gtk.Box+BoxChild
			this.addPreferenceButton = new global::Gtk.Button ();
			this.addPreferenceButton.CanFocus = true;
			this.addPreferenceButton.Name = "addPreferenceButton";
			this.addPreferenceButton.UseUnderline = true;
			this.addPreferenceButton.BorderWidth = ((uint)(3));
			this.addPreferenceButton.Label = global::Mono.Unix.Catalog.GetString ("Add Preference");
			this.preferenceContentVboxTop.Add (this.addPreferenceButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.preferenceContentVboxTop [this.addPreferenceButton]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 1;
			w5.Expand = false;
			w3.Add (this.preferenceContentVboxTop);
			this.PreferencesScrolledBox.Add (w3);
			this.vbox1.Add (this.PreferencesScrolledBox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.PreferencesScrolledBox]));
			w8.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.IconsTitleBox = new global::Gtk.HBox ();
			this.IconsTitleBox.Name = "IconsTitleBox";
			this.IconsTitleBox.Spacing = 6;
			this.IconsTitleBox.BorderWidth = ((uint)(3));
			// Container child IconsTitleBox.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Icons :</span>");
			this.label3.UseMarkup = true;
			this.IconsTitleBox.Add (this.label3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.IconsTitleBox [this.label3]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox1.Add (this.IconsTitleBox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.IconsTitleBox]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.IconsScrolledBox = new global::Gtk.ScrolledWindow ();
			this.IconsScrolledBox.CanFocus = true;
			this.IconsScrolledBox.Name = "IconsScrolledBox";
			this.IconsScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.IconsScrolledBox.BorderWidth = ((uint)(3));
			// Container child IconsScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w11 = new global::Gtk.Viewport ();
			w11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.iconsVbox = new global::Gtk.VBox ();
			this.iconsVbox.Name = "iconsVbox";
			this.iconsVbox.Spacing = 6;
			w11.Add (this.iconsVbox);
			this.IconsScrolledBox.Add (w11);
			this.vbox1.Add (this.IconsScrolledBox);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.IconsScrolledBox]));
			w14.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SplashTitleBox = new global::Gtk.HBox ();
			this.SplashTitleBox.Name = "SplashTitleBox";
			this.SplashTitleBox.Spacing = 6;
			this.SplashTitleBox.BorderWidth = ((uint)(3));
			// Container child SplashTitleBox.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<span font_weight=\"bold\">Splash Screens :</span>");
			this.label4.UseMarkup = true;
			this.SplashTitleBox.Add (this.label4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.SplashTitleBox [this.label4]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox1.Add (this.SplashTitleBox);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SplashTitleBox]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.SplashScrolledBox = new global::Gtk.ScrolledWindow ();
			this.SplashScrolledBox.CanFocus = true;
			this.SplashScrolledBox.Name = "SplashScrolledBox";
			this.SplashScrolledBox.ShadowType = ((global::Gtk.ShadowType)(1));
			this.SplashScrolledBox.BorderWidth = ((uint)(3));
			// Container child SplashScrolledBox.Gtk.Container+ContainerChild
			global::Gtk.Viewport w17 = new global::Gtk.Viewport ();
			w17.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.splashesVbox = new global::Gtk.VBox ();
			this.splashesVbox.WidthRequest = 0;
			this.splashesVbox.Name = "splashesVbox";
			this.splashesVbox.Spacing = 6;
			w17.Add (this.splashesVbox);
			this.SplashScrolledBox.Add (w17);
			this.vbox1.Add (this.SplashScrolledBox);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.SplashScrolledBox]));
			w20.Position = 5;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
