
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class AndroidWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.AndroidWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PhoneGapProjectAssistant.AndroidWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
