
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class PhoneGapProjectManagerWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label nameLabel;
		
		private global::Gtk.Label pathLabel;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.ComboBox platformCombobox;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.Entry versionEntry;
		
		private global::Gtk.Button button157;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Entry authorEntry;
		
		private global::Gtk.Entry descriptionEntry;
		
		private global::Gtk.Entry emailEntry;
		
		private global::Gtk.Entry idEntry;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry nameEntry;
		
		private global::Gtk.Entry originEntry;
		
		private global::Gtk.Entry sourceEntry;
		
		private global::Gtk.Entry websiteEntry;
		
		private global::Gtk.Notebook platformNotebook;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button button619;
		
		private global::Gtk.Button button163;
		
		private global::Gtk.Button button164;
		
		private global::Gtk.Button button165;
		
		private global::Gtk.Button button166;
		
		private global::Gtk.HButtonBox hbuttonbox2;
		
		private global::Gtk.Button button158;
		
		private global::Gtk.Button button159;
		
		private global::Gtk.Button button125;
		
		private global::Gtk.Button button160;
		
		private global::Gtk.Button button162;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PhoneGapProjectAssistant.PhoneGapProjectManagerWindow
			this.Name = "PhoneGapProjectAssistant.PhoneGapProjectManagerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PhoneGapProjectManagerWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(3));
			// Container child PhoneGapProjectAssistant.PhoneGapProjectManagerWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.nameLabel = new global::Gtk.Label ();
			this.nameLabel.Name = "nameLabel";
			this.nameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.nameLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.nameLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.pathLabel = new global::Gtk.Label ();
			this.pathLabel.Name = "pathLabel";
			this.pathLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.hbox1.Add (this.pathLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.pathLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox1.Add (this.fixed3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed3]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Target:");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.platformCombobox = global::Gtk.ComboBox.NewText ();
			this.platformCombobox.Name = "platformCombobox";
			this.hbox1.Add (this.platformCombobox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.platformCombobox]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Version:");
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.versionEntry = new global::Gtk.Entry ();
			this.versionEntry.WidthRequest = 45;
			this.versionEntry.CanFocus = true;
			this.versionEntry.Name = "versionEntry";
			this.versionEntry.IsEditable = true;
			this.versionEntry.InvisibleChar = '●';
			this.alignment1.Add (this.versionEntry);
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment1]));
			w8.Position = 6;
			w8.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button157 = new global::Gtk.Button ();
			this.button157.CanFocus = true;
			this.button157.Name = "button157";
			this.button157.UseUnderline = true;
			this.button157.Label = global::Mono.Unix.Catalog.GetString ("Rebuild");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.button157.Image = w9;
			this.hbox1.Add (this.button157);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button157]));
			w10.Position = 7;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.authorEntry = new global::Gtk.Entry ();
			this.authorEntry.CanFocus = true;
			this.authorEntry.Name = "authorEntry";
			this.authorEntry.IsEditable = true;
			this.authorEntry.InvisibleChar = '●';
			this.table1.Add (this.authorEntry);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1 [this.authorEntry]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.descriptionEntry = new global::Gtk.Entry ();
			this.descriptionEntry.CanFocus = true;
			this.descriptionEntry.Name = "descriptionEntry";
			this.descriptionEntry.IsEditable = true;
			this.descriptionEntry.InvisibleChar = '●';
			this.table1.Add (this.descriptionEntry);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1 [this.descriptionEntry]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.emailEntry = new global::Gtk.Entry ();
			this.emailEntry.CanFocus = true;
			this.emailEntry.Name = "emailEntry";
			this.emailEntry.IsEditable = true;
			this.emailEntry.InvisibleChar = '●';
			this.table1.Add (this.emailEntry);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.emailEntry]));
			w15.LeftAttach = ((uint)(3));
			w15.RightAttach = ((uint)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.idEntry = new global::Gtk.Entry ();
			this.idEntry.CanFocus = true;
			this.idEntry.Name = "idEntry";
			this.idEntry.IsEditable = true;
			this.idEntry.InvisibleChar = '●';
			this.table1.Add (this.idEntry);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.idEntry]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Id:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Author:");
			this.table1.Add (this.label10);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Email:");
			this.table1.Add (this.label11);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.label11]));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Website:");
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label12]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Origin:");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Source:");
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.label6]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Name:");
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Description:");
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label8]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameEntry = new global::Gtk.Entry ();
			this.nameEntry.CanFocus = true;
			this.nameEntry.Name = "nameEntry";
			this.nameEntry.IsEditable = true;
			this.nameEntry.InvisibleChar = '●';
			this.table1.Add (this.nameEntry);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameEntry]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.originEntry = new global::Gtk.Entry ();
			this.originEntry.CanFocus = true;
			this.originEntry.Name = "originEntry";
			this.originEntry.IsEditable = true;
			this.originEntry.InvisibleChar = '●';
			this.table1.Add (this.originEntry);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.originEntry]));
			w26.TopAttach = ((uint)(2));
			w26.BottomAttach = ((uint)(3));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.sourceEntry = new global::Gtk.Entry ();
			this.sourceEntry.CanFocus = true;
			this.sourceEntry.Name = "sourceEntry";
			this.sourceEntry.IsEditable = true;
			this.sourceEntry.InvisibleChar = '●';
			this.table1.Add (this.sourceEntry);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.sourceEntry]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.LeftAttach = ((uint)(3));
			w27.RightAttach = ((uint)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.websiteEntry = new global::Gtk.Entry ();
			this.websiteEntry.CanFocus = true;
			this.websiteEntry.Name = "websiteEntry";
			this.websiteEntry.IsEditable = true;
			this.websiteEntry.InvisibleChar = '●';
			this.table1.Add (this.websiteEntry);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.websiteEntry]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(3));
			w28.RightAttach = ((uint)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.platformNotebook = new global::Gtk.Notebook ();
			this.platformNotebook.CanFocus = true;
			this.platformNotebook.Name = "platformNotebook";
			this.platformNotebook.CurrentPage = -1;
			this.platformNotebook.Scrollable = true;
			this.platformNotebook.BorderWidth = ((uint)(3));
			this.vbox1.Add (this.platformNotebook);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.platformNotebook]));
			w30.Position = 3;
			w30.Padding = ((uint)(2));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button619 = new global::Gtk.Button ();
			this.button619.CanFocus = true;
			this.button619.Name = "button619";
			this.button619.UseUnderline = true;
			this.button619.Label = global::Mono.Unix.Catalog.GetString ("Update config");
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.button619.Image = w31;
			this.hbuttonbox1.Add (this.button619);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button619]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button163 = new global::Gtk.Button ();
			this.button163.CanFocus = true;
			this.button163.Name = "button163";
			this.button163.UseUnderline = true;
			this.button163.Label = global::Mono.Unix.Catalog.GetString ("Clean");
			global::Gtk.Image w33 = new global::Gtk.Image ();
			w33.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.button163.Image = w33;
			this.hbuttonbox1.Add (this.button163);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button163]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button164 = new global::Gtk.Button ();
			this.button164.CanFocus = true;
			this.button164.Name = "button164";
			this.button164.UseUnderline = true;
			this.button164.Label = global::Mono.Unix.Catalog.GetString ("Build");
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
			this.button164.Image = w35;
			this.hbuttonbox1.Add (this.button164);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button164]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button165 = new global::Gtk.Button ();
			this.button165.CanFocus = true;
			this.button165.Name = "button165";
			this.button165.UseUnderline = true;
			this.button165.Label = global::Mono.Unix.Catalog.GetString ("Emulate");
			this.hbuttonbox1.Add (this.button165);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button165]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.button166 = new global::Gtk.Button ();
			this.button166.CanFocus = true;
			this.button166.Name = "button166";
			this.button166.UseUnderline = true;
			this.button166.Label = global::Mono.Unix.Catalog.GetString ("Run");
			global::Gtk.Image w38 = new global::Gtk.Image ();
			w38.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			this.button166.Image = w38;
			this.hbuttonbox1.Add (this.button166);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.button166]));
			w39.Position = 4;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w40.Position = 4;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.Spacing = 10;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button158 = new global::Gtk.Button ();
			this.button158.CanFocus = true;
			this.button158.Name = "button158";
			this.button158.UseUnderline = true;
			this.button158.Label = global::Mono.Unix.Catalog.GetString ("Close");
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			this.button158.Image = w41;
			this.hbuttonbox2.Add (this.button158);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button158]));
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button159 = new global::Gtk.Button ();
			this.button159.CanFocus = true;
			this.button159.Name = "button159";
			this.button159.UseUnderline = true;
			this.button159.Label = global::Mono.Unix.Catalog.GetString ("Reveal in Finder");
			global::Gtk.Image w43 = new global::Gtk.Image ();
			w43.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-directory", global::Gtk.IconSize.Menu);
			this.button159.Image = w43;
			this.hbuttonbox2.Add (this.button159);
			global::Gtk.ButtonBox.ButtonBoxChild w44 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button159]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button125 = new global::Gtk.Button ();
			this.button125.CanFocus = true;
			this.button125.Name = "button125";
			this.button125.UseUnderline = true;
			this.button125.Label = global::Mono.Unix.Catalog.GetString ("Open Xcode");
			this.hbuttonbox2.Add (this.button125);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button125]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button160 = new global::Gtk.Button ();
			this.button160.CanFocus = true;
			this.button160.Name = "button160";
			this.button160.UseUnderline = true;
			this.button160.Label = global::Mono.Unix.Catalog.GetString ("Manage plugins");
			this.hbuttonbox2.Add (this.button160);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button160]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.button162 = new global::Gtk.Button ();
			this.button162.CanFocus = true;
			this.button162.Name = "button162";
			this.button162.UseUnderline = true;
			this.button162.Label = global::Mono.Unix.Catalog.GetString ("Edit config.xml");
			this.hbuttonbox2.Add (this.button162);
			global::Gtk.ButtonBox.ButtonBoxChild w47 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.button162]));
			w47.Position = 4;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox1.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox2]));
			w48.Position = 5;
			w48.Expand = false;
			w48.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 691;
			this.DefaultHeight = 719;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button157.Clicked += new global::System.EventHandler (this.RebuildPlatformClicked);
			this.button619.Clicked += new global::System.EventHandler (this.UpdateClicked);
			this.button163.Clicked += new global::System.EventHandler (this.CleanClicked);
			this.button164.Clicked += new global::System.EventHandler (this.BuildClicked);
			this.button165.Clicked += new global::System.EventHandler (this.EmulateClicked);
			this.button166.Clicked += new global::System.EventHandler (this.RunClicked);
			this.button158.Clicked += new global::System.EventHandler (this.OnCloseClicked);
			this.button159.Clicked += new global::System.EventHandler (this.OpenInFinder);
			this.button125.Clicked += new global::System.EventHandler (this.OpenXCodeClicked);
		}
	}
}
