
// This file has been generated by the GUI designer. Do not modify.
namespace PhoneGapProjectAssistant
{
	public partial class AddSplashIcon
	{
		public virtual void Build ()
		{
			// Action group PhoneGapProjectAssistant.AddSplashIcon
		}
	}
}
